import { WorshipPlace, Sermon, MasjidAdminAccount } from './types';

export const INITIAL_WORSHIP_PLACES: WorshipPlace[] = [
  {
    id: 'place-1',
    name: 'Al-Farooq Central Grand Mosque',
    religion: 'Islam',
    venueType: 'Mosque / Masjid',
    congregationDay: 'Friday',
    city: 'Manchester',
    country: 'United Kingdom',
    address: '142 Wilmslow Road, Rusholme, Manchester M14 5REV',
    imageUrl: 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&q=80&w=800',
    adminName: 'Dr. Tariq Al-Mansoor',
    preacherTitle: 'Imam & Khatib',
    preacherName: 'Sheikh Muhammad Al-Azhari',
    contactEmail: 'admin@alfarooqmosque.org',
    contactPhone: '+44 161 224 8920',
    description: 'A vibrant community hub providing daily prayers, Friday Jummah Khutbah in original Arabic with live translation, youth education, and interfaith dialogue.',
    followerCount: 1420,
    languagesOffered: ['Arabic', 'English', 'Urdu', 'Bengali', 'Turkish'],
    lat: 53.4808,
    lng: -2.2426,
    approvalStatus: 'approved',
    createdAt: '2026-01-15',
    facilities: ['Wudu Area', 'Ladies Section', 'Wheelchair Access', 'Parking', 'Quran Academy', 'Funeral Service'],
  },
  {
    id: 'place-2',
    name: 'St. Jude Community Church & Cathedral',
    religion: 'Christianity',
    venueType: 'Church',
    congregationDay: 'Sunday',
    city: 'Chicago',
    country: 'United States',
    address: '840 N Michigan Ave, Chicago, IL 60611',
    imageUrl: 'https://images.unsplash.com/photo-1548625361-1851e360e5ff?auto=format&fit=crop&q=80&w=800',
    adminName: 'Sister Eleanor Vance',
    preacherTitle: 'Senior Pastor',
    preacherName: 'Rev. David Harrison',
    contactEmail: 'pastor@stjudechicago.org',
    contactPhone: '+1 312 555 0192',
    description: 'An open and welcoming Christian congregation broadcasting Sunday sermon homilies globally for worshippers seeking faith, unity, and hope.',
    followerCount: 980,
    languagesOffered: ['English', 'Spanish', 'French', 'Swahili', 'German'],
    lat: 41.8781,
    lng: -87.6298,
    approvalStatus: 'approved',
    createdAt: '2026-02-01',
    facilities: ['Wheelchair Access', 'Community Hall', 'Choir Loft', 'Parking'],
  },
  {
    id: 'place-3',
    name: 'Sri Laxmi Narayan Temple',
    religion: 'Hinduism',
    venueType: 'Mandir / Temple',
    congregationDay: 'Sunday',
    city: 'Toronto',
    country: 'Canada',
    address: '240 Markham Rd, Scarborough, ON M1J 3C4',
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&q=80&w=800',
    adminName: 'Rajesh Sharma',
    preacherTitle: 'Head Acharya & Priest',
    preacherName: 'Pandit Rameshwar Shastri',
    contactEmail: 'contact@laxminarayantemple.ca',
    contactPhone: '+1 416 555 3841',
    description: 'Promoting Vedic teachings, Bhagavad Gita discourses, and spiritual devotion. Weekly Sunday Satsang and moral sermons.',
    followerCount: 810,
    languagesOffered: ['Hindi', 'Sanskrit', 'English', 'Gujarati', 'Tamil'],
    lat: 43.6532,
    lng: -79.3832,
    approvalStatus: 'approved',
    createdAt: '2026-02-20',
    facilities: ['Prasadam Dining', 'Cultural Center', 'Parking'],
  },
  {
    id: 'place-4',
    name: 'Beth Shalom Synagogue',
    religion: 'Judaism',
    venueType: 'Synagogue',
    congregationDay: 'Saturday',
    city: 'Melbourne',
    country: 'Australia',
    address: '15 Alma Rd, St Kilda VIC 3182',
    imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    adminName: 'Miriam Klein',
    preacherTitle: 'Rabbi',
    preacherName: 'Rabbi Jonathan Stern',
    contactEmail: 'office@bethshalom.org.au',
    contactPhone: '+61 3 9534 1022',
    description: 'Shabbat morning Torah readings, sermon commentary, and community study exploring ancient ethics in modern life.',
    followerCount: 530,
    languagesOffered: ['Hebrew', 'English', 'Russian', 'Spanish'],
    lat: -37.8136,
    lng: 144.9631,
    approvalStatus: 'approved',
    createdAt: '2026-03-05',
    facilities: ['Kosher Kitchen', 'Judaica Library', 'Wheelchair Access'],
  },
  {
    id: 'place-5',
    name: 'Gurdwara Sri Guru Nanak Dev Ji',
    religion: 'Sikhism',
    venueType: 'Gurdwara',
    congregationDay: 'Sunday',
    city: 'Birmingham',
    country: 'United Kingdom',
    address: '188 Soho Road, Handsworth, Birmingham B21 9LN',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=800',
    adminName: 'Gurpreet Singh',
    preacherTitle: 'Head Granthi',
    preacherName: 'Bhai Harvinder Singh',
    contactEmail: 'info@gurdwarabirmingham.org',
    contactPhone: '+44 121 551 4200',
    description: 'Serving community langar and daily Gurbani Kirtan with weekly Katha discourses explaining universal brotherhood and devotion.',
    followerCount: 1150,
    languagesOffered: ['Punjabi', 'English', 'Hindi'],
    lat: 52.4862,
    lng: -1.8904,
    approvalStatus: 'approved',
    createdAt: '2026-03-12',
    facilities: ['Langar Hall', '24/7 Community Kitchen', 'Sangat School'],
  },
  {
    id: 'place-6',
    name: 'Al-Noor Islamic Center & Masjid',
    religion: 'Islam',
    venueType: 'Mosque / Masjid',
    congregationDay: 'Friday',
    city: 'Chicago',
    country: 'United States',
    address: '6201 N Lincoln Ave, Chicago, IL 60659',
    imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
    adminName: 'Sheikh Bilal Al-Sayed',
    preacherTitle: 'Imam & Resident Scholar',
    preacherName: 'Imam Bilal Al-Sayed',
    contactEmail: 'contact@alnoorchicago.org',
    contactPhone: '+1 773 555 9012',
    description: 'Newly registered community center seeking verification. Offers daily 5-time prayers, Jummah khutbahs, and youth sports.',
    followerCount: 320,
    languagesOffered: ['Arabic', 'English', 'Urdu'],
    lat: 41.9942,
    lng: -87.7083,
    approvalStatus: 'pending',
    createdAt: '2026-07-28',
    facilities: ['Wudu Area', 'Parking', 'Youth Gym'],
  },
  {
    id: 'place-7',
    name: 'Madina Jamia Masjid & Education Center',
    religion: 'Islam',
    venueType: 'Mosque / Masjid',
    congregationDay: 'Friday',
    city: 'London',
    country: 'United Kingdom',
    address: '213 Whitechapel Rd, London E1 1DE',
    imageUrl: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=80&w=800',
    adminName: 'Hafiz Farooq Hassan',
    preacherTitle: 'Head Imam',
    preacherName: 'Shaykh Farooq Hassan',
    contactEmail: 'admin@madinamasjidlondon.org',
    contactPhone: '+44 20 7377 2200',
    description: 'Pending verification submission. Central London mosque hosting multi-lingual Friday sermons and Hifz Quran classes.',
    followerCount: 650,
    languagesOffered: ['Arabic', 'English', 'Bengali', 'Urdu'],
    lat: 51.5186,
    lng: -0.0612,
    approvalStatus: 'pending',
    createdAt: '2026-07-30',
    facilities: ['Wudu Area', 'Ladies Prayer Hall', 'Library', 'Classrooms'],
  }
];

export const INITIAL_PENDING_ADMIN_ACCOUNTS: MasjidAdminAccount[] = [
  {
    id: 'admin-req-1',
    fullName: 'Imam Farooq Hassan',
    email: 'admin@madinamasjidlondon.org',
    phone: '+44 7700 900123',
    placeId: 'place-7',
    placeName: 'Madina Jamia Masjid & Education Center',
    role: 'masjid_admin',
    status: 'pending',
    requestedAt: '2026-07-30 14:22',
  },
  {
    id: 'admin-req-2',
    fullName: 'Sheikh Bilal Al-Sayed',
    email: 'contact@alnoorchicago.org',
    phone: '+1 312 555 8810',
    placeId: 'place-6',
    placeName: 'Al-Noor Islamic Center & Masjid',
    role: 'masjid_admin',
    status: 'pending',
    requestedAt: '2026-07-28 09:15',
  },
  {
    id: 'admin-req-3',
    fullName: 'Dr. Tariq Al-Mansoor',
    email: 'admin@alfarooqmosque.org',
    phone: '+44 161 224 8920',
    placeId: 'place-1',
    placeName: 'Al-Farooq Central Grand Mosque',
    role: 'masjid_admin',
    status: 'approved',
    requestedAt: '2026-01-15 10:00',
    approvedAt: '2026-01-15 11:30',
  }
];

export const INITIAL_SERMONS: Sermon[] = [
  {
    id: 'sermon-1',
    placeId: 'place-1',
    placeName: 'Al-Farooq Central Grand Mosque',
    religion: 'Islam',
    title: 'خطبة الجمعة: أهمية الصبر والتوكل والتراحم في حياة المسلم',
    speakerName: 'Sheikh Muhammad Al-Azhari',
    speakerTitle: 'Imam & Khatib',
    originalLanguage: 'Arabic',
    originalLanguageCode: 'ar',
    date: '2026-07-31',
    scriptureReference: 'Surah Al-Baqarah (2:153) & Surah Al-Inshirah (94:5-6)',
    topicTags: ['Patience (Sabr)', 'Trust in God (Tawakkul)', 'Community Kindness', 'Friday Jummah'],
    summary: 'A soul-enriching Friday Khutbah focusing on cultivating inner patience (Sabr) during trials, maintaining firm trust in Divine Providence (Tawakkul), and showing active mercy towards neighbors and the vulnerable.',
    keyTakeaways: [
      'Sabr is not passive endurance, but active perseverance rooted in faith.',
      'True Tawakkul requires taking practical measures while holding heart reliance upon God.',
      'Every act of kindness towards family and community reflects true spiritual sincerity.'
    ],
    originalText: `الحمد لله رب العالمين، والصلاة والسلام على أشرف الأنبياء والمرسلين نبينا محمد وعلى آله وصحبه أجمعين.

أما بعد، فيا أيها المسلمون: اتقوا الله تعالى واعلموا أن الحياة الدنيا دار ابتلاء واختبار، ولا يثبت فيها إلا من تزين بحليتي الصبر واليقين. قال الله تعالى: {يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلاةِ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ}.

إن الصبر ليس عجزاً ولا استسلاماً، بل هو قوة إيمانية تحجز صاحبها عن الجزع والتسخط، وتدعه يواجه أقدار الله برضا وثبات. ومع الصبر يأتي التوكل الصادق، الذي تجمع فيه بين بذل الأسباب المشروعة مع قطع التعلق بها والاعتماد التام على المسبب سبحانه.

كما يوصينا ديننا الحنيف بالرحمة والتكافل بين أبناء المجتمع؛ فالرحماء يرحمهم الرحمن. احرصوا على تفقد جيرانكم، وإغاثة الملهوفين، وإفشاء السلام والابتسامة في وجوه العباد.

نسأل الله تعالى أن يملأ قلوبنا إيماناً وصابراً، وأن يجعلنا من عباده الصالحين. أقول قولي هذا وأستغفر الله لي ولكم.`
  },
  {
    id: 'sermon-2',
    placeId: 'place-2',
    placeName: 'St. Jude Community Church & Cathedral',
    religion: 'Christianity',
    title: 'Walking in Light: Compassion in an Uncertain World',
    speakerName: 'Rev. David Harrison',
    speakerTitle: 'Senior Pastor',
    originalLanguage: 'English',
    originalLanguageCode: 'en',
    date: '2026-07-26',
    scriptureReference: 'Matthew 5:14-16 & Colossians 3:12-14',
    topicTags: ['Compassion', 'Hope', 'Grace', 'Sunday Homily'],
    summary: 'Reflecting on Jesus’ calling for believers to be the light of the world, offering healing, practical benevolence, and unconditional forgiveness to all people.',
    keyTakeaways: [
      'Light is meant to illuminate darkness through concrete acts of kindness.',
      'Forgiveness heals the giver as much as the receiver.',
      'Active listening and empathy build bridges across broken relationships.'
    ],
    originalText: `Grace and peace to you, brothers and sisters. Today we gather under the warm promise that love overcomes fear. In our Scripture reading from Matthew, Jesus tells us: "You are the light of the world. A city built on a hill cannot be hidden."

What does it mean to be light today? It means bringing warmth to cold hearts, bringing hope to those crushed by sorrow, and refusing to let cynicism dictate how we treat our neighbors. 

When we choose compassion over judgment, we mirror the divine grace extended to each of us. Let this Sunday be a catalyst for action—reach out to someone lonely, offer forgiveness where bitterness has taken root, and stand up for justice in your city.`
  },
  {
    id: 'sermon-3',
    placeId: 'place-3',
    placeName: 'Sri Laxmi Narayan Temple',
    religion: 'Hinduism',
    title: 'कर्मयोग और आन्तरिक शांति: श्रीमद्भगवद्गीता सार',
    speakerName: 'Pandit Rameshwar Shastri',
    speakerTitle: 'Head Acharya & Priest',
    originalLanguage: 'Hindi',
    originalLanguageCode: 'hi',
    date: '2026-07-26',
    scriptureReference: 'Srimad Bhagavad Gita Chapter 2, Verse 47',
    topicTags: ['Karma Yoga', 'Inner Peace', 'Dharma', 'Sunday Satsang'],
    summary: 'A deep discourse explaining the principle of Karma Yoga—performing righteous actions with dedication without attached anxiety over results.',
    keyTakeaways: [
      'Focus on purity of intention and action rather than selfish expectation.',
      'Mindfulness in daily duties transforms ordinary routine into sacred devotion.',
      'Equanimity of mind in success and failure is true yoga.'
    ],
    originalText: `कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥

प्रिय सनातन बंधुओं, भगवान श्रीकृष्ण अर्जुन को गीता में निष्काम कर्म का अमर संदेश देते हैं। जब हम अपने दैनिक जीवन में अपने कर्तव्यों का पालन बिना अहंकार और बिना फल की चिंता के करते हैं, तो हमारा मन शांत और पवित्र होता है।

सच्चा धर्म केवल पूजा पाठ में नहीं, बल्कि हमारी वाणी, व्यवहार और परोपकार में है। जब हम समाज के लिए सेवा भाव से कर्म करते हैं, तो वह भक्ति का ही उत्तम रूप बन जाता है। अपने मन को समता में स्थापित करें और ईश्वर के विधान पर विश्वास रखें।`
  },
  {
    id: 'sermon-4',
    placeId: 'place-4',
    placeName: 'Beth Shalom Synagogue',
    religion: 'Judaism',
    title: 'Torah Portion Shabbat: Building Bridges Through Chesed and Truth',
    speakerName: 'Rabbi Jonathan Stern',
    speakerTitle: 'Rabbi',
    originalLanguage: 'English',
    originalLanguageCode: 'en',
    date: '2026-07-25',
    scriptureReference: 'Deuteronomy 16:20 & Psalm 85:11',
    topicTags: ['Justice (Tzedek)', 'Loving Kindness (Chesed)', 'Shabbat', 'Community'],
    summary: 'A Shabbat morning address exploring the dual imperative of pursuing justice (Tzedek) while upholding loving kindness (Chesed) in everyday discourse.',
    keyTakeaways: [
      'Justice without kindness can become rigid; kindness without truth lacks grounding.',
      'Small acts of hospitality (Hachnasat Orchim) mend tears in our social fabric.',
      'Shabbat is an sanctuary in time to realign our moral compass.'
    ],
    originalText: `Shabbat Shalom to everyone joining us. As we reflect on this week's Parasha, we encounter the famous mandate: "Tzedek, tzedek tirdof"—Justice, justice shall you pursue. 

Our sages asked why the word "justice" is repeated. One commentary teaches that we must pursue just ends through just means. In a world increasingly prone to division, our calling is to embody Chesed (loving-kindness) alongside our pursuit of truth. When we open our homes and hearts to others, we sanctify God's name.`
  }
];
